FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy python dependency manifest
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy frontend source code
COPY frontend /app/frontend

# Expose Streamlit UI port
EXPOSE 8501

# Start Streamlit application
CMD ["streamlit", "run", "frontend/app.py", "--server.address=0.0.0.0", "--server.port=8501"]
